### ISSUE TITLE
Webview error crashing applications

### ISSUE THREAD

**Issue by drsood** [crdroidandroid/issue_tracker#444]
### Issue type

User interface

### Device

Poco F4 (munch)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-17

### Bug description

Multiple Webview based apps are crashing when opening them. Initially after a reboot, they work ok for some time.

### Steps to reproduce

Open webview based apps (like Amazon, Phonepe etc)

### Relevant log (logcat/build log)

```shell
FATAL EXCEPTION: main
Process: com.phonepe.app, PID: 27374
java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.phonepe.app (pid 27374), lock owner  unknown
	at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle6432.aab-stable-636717933:201)
	at org.chromium.android_webview.AwBrowserProcess.j(chromium-TrichromeWebViewGoogle6432.aab-stable-636717933:16)
	at com.android.webview.chromium.L.d(chromium-TrichromeWebViewGoogle6432.aab-stable-636717933:203)
	at WV.QY.run(chromium-TrichromeWebViewGoogle6432.aab-stable-636717933:8)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8498)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)


FATAL EXCEPTION: main
Process: in.amazon.mShop.android.shopping, PID: 29401
java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process in.amazon.mShop.android.shopping (pid 29401), lock owner  unknown
	at org.chromium.android_webview.AwDataDirLock.b(chromium-SystemWebView64.apk-stable-636721804:180)
	at org.chromium.android_webview.AwBrowserProcess.j(chromium-SystemWebView64.apk-stable-636721804:16)
	at com.android.webview.chromium.L.e(chromium-SystemWebView64.apk-stable-636721804:167)
	at WV.SK.run(chromium-SystemWebView64.apk-stable-636721804:8)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8498)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

### Solution

Rebooting the phone fixes the application crash for some time

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
upstream webview issue
not crDroid related, but may get fixed with next webview updates

**Comment by drsood** [comment]
Well, I tried disabling / uninstalling the default Webview present in the system partition, and replaced it with the Google Webview installed from Play Store app. I also tried installing this playstore webview as system app. But I still face the same error in multiple apps.

Should this not have disapperared if it was related to the already installed webview? Doesnt that indicate indirectly that the error is in someway related to crDroid? The ROM has basically become difficult to use because of these continuous errors. Please suggest some solution

**Comment by gwolf2u** [comment]
there are framework dependencies that need to be addressed
you can't just add as system app
suggest clean flash with crdroid nikgapps
