### ISSUE TITLE
bug: audio over usb crackly (buffer underflow), alioth

### ISSUE THREAD

**Issue by defvs** [crdroidandroid/issue_tracker#526]
### Issue type

Feature not working as intended

### Device

alioth

### crDroid version

crDroid 10

### Exact version / Build date

10.8/2024-09-27

### Bug description

Similar bug to #479 

It seems to have been fixed for most apps, however some apps such as Plexamp still have issues with audio over a USB DAC (mine is a FIIO KA11).

Playing audio results in a logcat spam of:
```
09-28 18:43:21.487 W/audio_hw_primary(1128): out_get_presentation_position: avail:1008 > kernel_buffer_size:1008 clamping!
09-28 18:43:21.489 W/audio_hw_primary(1128): out_write: underrun(93639) frames_by_time(638) > out->last_fifo_frames_remaining(504)
```

As well as audio crackle, making it unusable.

### Steps to reproduce

.

### Relevant log (logcat/build log)

```shell
.
```

### Solution

It seems like keeping the CPU busy (enabling the visualizer of Plexamp, for example) makes the issue disappear. However, I guess it is an issue with the buffer being too small by default.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Since I fixed most of the USB audio issues on previous builds, this would be a thougher one since imo only app related and not a general issue atm.
You stated all's working on VLC and no underruns, only Plexamp right?
For what it's worth, did you try any other roms to rule out some source issue?
Did it ever worked well on previous crDroid builds for that matter?

**Comment by raystef66** [comment]
@defvs  did you check the above message?
Also, still happening on 0.2.11 build?
Tried cr11?

**Comment by defvs** [comment]
Will be testing tonight. Sorry, totally missed your message.
I haven't tried with previous builds. On other ROMs, no issues at all.

**Comment by defvs** [comment]
crDroid 10.9, build of Nov 9 2024:
Audio is not crackly anymore, which is very good news. However, there are still tons of buffer underruns in the log, so it seems the underlying bug is still present, although not as severe. I didn't have much time to fully test out and see if it would be crackly during a long listening session, so I will report back in a couple of days to finally close this issue.
Thanks for the time you are giving for the ROM development raystef66.

![image](https://github.com/user-attachments/assets/dfa78936-f2f8-424a-bd79-615be167566e)

**Comment by raystef66** [comment]
@defvs 
Good to hear it has improved. Keep an eye on it and if possible feedback again.
Also, feel free to send a log here again on the underrun so I can take a look at it again.

**Comment by defvs** [comment]
Sure thing. Here's a logcat with the following steps done during the recording:
- Plugging in the USB audio device
- Switching to Plexamp
- Pressing "play"
- Shutting off the display for about 15 seconds
- Turning it back on, pressing "pause"

[2024-11-12-10-44-44.txt](https://github.com/user-attachments/files/17714479/2024-11-12-10-44-44.txt)

**Comment by defvs** [comment]
I tested it again today, the audio is still crackly, maybe last time was a fluke?

**Comment by raystef66** [comment]
> I tested it again today, the audio is still crackly, maybe last time was a fluke?

Still, on like VLC it still doens't occur right?
Also, which ROM did you test on which crackling doesn't happen (VLC as well as Plexamp)?

**Comment by raystef66** [comment]
@defvs btw could you give cr11 a try?

**Comment by raystef66** [comment]
@defvs  Try this modules as audio being updated on audio HAL 7.1. Also 24bit audio playback.
Give it a try and let me know.
[alioth_wiredheadsetFix_16112024_raystef66.zip](https://github.com/user-attachments/files/17784212/alioth_wiredheadsetFix_16112024_raystef66.zip)

**Comment by raystef66** [comment]
Closed because of no feedback given.

**Comment by defvs** [comment]
Sorry, totally forgot about this.
Updated to crDroid. Same exact issue, no change.
